[package]
name = "uuid2clip"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.2.1"
notify-rust = "4.9.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng", "macro-diagnostics"]
